---
- name: "Install PHP"
  homebrew:
    name: "{{item}}"
    state: "latest"
    update_homebrew: true
    upgrade_all: true
  with_items:
    - "composer"
    - "php"
    - "php-code-sniffer"
    - "php-cs-fixer"
    - "phplint"

- name: "Copy php.ini"
  copy:
    src: "php.ini"
    dest: "/usr/local/etc/php/php.ini"
    backup: true
