- name: System settings
  block:
    - name: Disable create .DS_Store file on network drive
      command: |
        defaults write com.apple.desktopservices DSDontWriteNetworkStores True
      notify: restart finder

    - name: Change to show hidden files
      command: |
        defaults write com.apple.finder AppleShowAllFiles TRUE
      notify: restart finder
  become: yes
  become_user: root

- name: Check if homebrew installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew

- name: Install homebrew
  command: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not homebrew.stat.exists

- name: Tap repositories
  homebrew_tap:
    name: "{{item}}"
    state: present
  with_items:
    - homebrew/cask-versions

