- name: System settings
  block:
    - name: Disable create .DS_Store file on network drive
      command: |
        defaults write com.apple.desktopservices DSDontWriteNetworkStores True
      notify: restart finder

    - name: Change to show hidden files
      command: |
        defaults write com.apple.finder AppleShowAllFiles TRUE
      notify: restart finder
  become: yes
  become_user: root

- name: Check if Homebrew installed
  block:
    - name: Check for Intel Mac
      stat:
        path: /usr/local/bin/brew
      register: homebrew
    - name: Check for M1 mac
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew
      when: not homebrew.stat.exists

- name: Fail if Homebrew is not installed
  block:
    - name: Please install Homebrew
      debug:
        msg:
          - Homebrew is not installed.
          - Execute the following command to install Homebrew.
          - ""
          - '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'

    - name: Fail if Homebrew is not installed
      fail:
        msg: Homebrew is not installed
  when: not homebrew.stat.exists

- name: Tap repositories
  homebrew_tap:
    name: "{{item}}"
    state: present
  with_items:
    - homebrew/cask-fonts
    - homebrew/cask-versions
    - knqyf263/pet

