---
- name: "Change SSH port"
  block:
    - name: "Copy LaunchDaemons service"
      template:
        src: "ssh.plist"
        dest: /Library/LaunchDaemons/{{domain.split('.') | reverse | join('.')}}.ssh.plist
        backup: true

    - name: "Unload ssh service"
      command: |
        launchctl unload -w "/System/Library/LaunchDaemons/ssh.plist"

    - name: "Load ssh service"
      command: |
        launchctl load -w /Library/LaunchDaemons/{{domain.split('.') | reverse | join('.')}}.ssh.plist
  become: true
  become_user: "root"
