---
packages:
  - "ansible"
  - "aria2"
  - "ast-grep"
  - "awscli"
  - "binutils"
  - "bat"
  - "brotli"
  - "cmake"
  - "colordiff"
  - "convmv"
  - "coreutils"
  - "ctop"
  - "diffutils"
  - "direnv"
  - "emacs"
  - "envchain"
  - "eza"
  - "findutils"
  - "flock"
  - "fd"
  - "fzf"
  - "gawk"
  - "git"
  - "git-delta"
  - "git-lfs"
  - "git-secret"
  - "global"
  - "glow"
  - "graphicsmagick"
  - "grc"
  - "gnu-getopt"
  - "gnu-sed"
  - "gnu-tar"
  - "grep"
  - "gzip"
  - "hexyl"
  - "htop"
  - "ipcalc"
  - "iproute2mac"
  - "jp2a"
  - "jq"
  - "lame"
  - "ldns"
  - "lhasa"
  - "lsd"
  - "lzip"
  - "moreutils"
  - "mosh"
  - "neovim"
  - "nkf"
  - "pass"
  - "pandoc"
  - "pbzip2"
  - "peco"
  - "pet"
  - "prettyping"
  - "pwgen"
  - "rclone"
  - "rdap"
  - "ripgrep"
  - "rlwrap"
  - "screen"
  - "sd"
  - "sl"
  - "sqlite"
  - "telnet"
  - "tig"
  - "tmux"
  - "tor"
  - "trash-cli"
  - "tree"
  - "unar"
  - "w3m"
  - "whois"
  - "yubikey-personalization"
  - "zsh-autosuggestions"
  - "zsh-completions"
  - "zstd"
