---
- name: "Setup Packet Filter"
  block:
    - name: "Copy anchors"
      template:
        src: "anchor.j2"
        dest: "/etc/pf.anchors/{{domain.split('.') | reverse | join('.')}}"
        backup: true

    - name: "Copy pf.conf"
      template:
        src: "pf.conf.j2"
        dest: "/etc/pf.conf"
        backup: true

    - name: "Copy LaunchDaemons service"
      template:
        src: "service.plist.j2"
        dest: "/Library/LaunchDaemons/{{domain.split('.') | reverse | join('.')}}.pfctl.plist"
        backup: true

    - name: "Unload pfctl service"
      command: |
        launchctl unload -w "/System/Library/LaunchDaemons/com.apple.pfctl.plist"

    - name: "Load pfctl service"
      command: |
        launchctl load -w /Library/LaunchDaemons/{{domain.split('.') | reverse | join('.')}}.pfctl.plist
  become: true
  become_user: "root"
