- name: Install unbound
  homebrew:
    name: "{{item}}"
    state: latest
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - unbound

- name: Copy unbound.conf
  copy:
    src: unbound.conf
    dest: /usr/local/etc/unbound/unbound.conf
    backup: yes

- name: Unsure unbound.conf.d directory
  file:
    path: /usr/local/etc/unbound/unbound.conf.d
    state: directory

- name: Copy unbound settings
  copy:
    src: "./unbound.conf.d/{{item}}"
    dest: /usr/local/etc/unbound/unbound.conf.d/{{item}}
    backup: yes
  with_items:
    - local-data.conf
    - local-zone.conf
    - qname-minimisation.conf
    - root-auto-trust-anchor-file.conf

- name: Copy unbound server setting
  template:
    src: "{{item}}.j2"
    dest: /usr/local/etc/unbound/unbound.conf.d/{{item}}
    backup: yes
  with_items:
    - server.conf

- name: Unsure trust anchor file directory
  file:
    path: /usr/local/var/lib/unbound
    state: directory

- name: Copy trust anchor file
  copy:
    src: root.key
    dest: /usr/local/var/lib/unbound/root.key

- name: Auto start unbound
  block:
    - name: Copy LaunchDaemons service
      template:
        src: unbound.plist.j2
        dest: /Library/LaunchDaemons/{{domain.split('.') | reverse | join('.')}}.unbound.plist
        backup: yes

    - name: Load unbound service
      command: |
        launchctl load -w /Library/LaunchDaemons/{{domain.split('.') | reverse | join('.')}}.unbound.plist
  become: yes
  become_user: root

