- name: Install packages
  homebrew_cask:
    name: "{{item}}"
    state: upgraded 
    update_homebrew: yes
  with_items:
    - android-studio
    - appcode
    - clion
    - intellij-idea
    - kotlin
    - rider

