- name: Install virtualbox 
  homebrew_cask:
    name: "{{item}}"
    state: upgraded 
    update_homebrew: yes
    upgrade_all: yes
  with_items:
    - vagrant
    - virtualbox
    - virtualbox-extension-pack

